language: node_js
node_js:
 - "node"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-extra # texlive-full
  - wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb && sudo dpkg -i pandoc-2.7.2-1-amd64.deb

install:
  - sudo apt-get install -y python-pip
  - sudo pip install codespell
  - npm install

script:
  - ./build-docs.sh
  - codespell -q4 *.md
  - npm run pkg
    # - docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `find . -name "*.md"`

before_deploy:
  - rm docs/*.md

deploy:
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      branch: master
  - deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: 
    - caou-linux
    - caou-macos
    - caou-win.exe
    - caou-pandoc-filter-linux
    - caou-pandoc-filter-macos
    - caou-pandoc-filter-win.exe
    skip_cleanup: true
    on:
      tags: true
